- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: python setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python



- name: copy the catalogue service and start and enable services
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd        

    
